---
- hosts: nodes
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: update hosts file
        template: src=./hosts.j2 dest=/etc/hosts
      - name: install mesosphere yum repo
        yum: name=http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present
      - name: install mesos and docker packages
        yum: pkg=device-mapper-event-libs,mesos,docker state=latest
      - name: configure dns
        template: src=./resolv.conf.j2 dest=/etc/resolv.conf 
      - name: configure containerizers
        lineinfile: dest=/etc/mesos-slave/containerizers create=yes line="docker,mesos"
      - name: set zookeeper master
        replace: dest=/etc/mesos/zk regexp="localhost" replace="192.168.33.10"
      - name: start mesos-slave
        service: name=mesos-slave state=started enabled=yes
      - name: start docker
        service: name=docker state=started enabled=yes
      - name: install outyet
        shell: docker load --input=/vagrant/outyet.tar.gz
